-- Side Quest Studios - Agent Fleet Schema
-- Generated by Milo

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- CORE DATA MODEL (4 Tables)
-- ============================================

-- Table: Agent Registry
-- Stores all agent identities and their capabilities
CREATE TABLE IF NOT EXISTS ops_agents (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL,
    capabilities TEXT[] DEFAULT '{}',
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'idle', 'busy', 'disabled')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: Mission Proposals
-- Agents propose ideas/actions here for approval
CREATE TABLE IF NOT EXISTS ops_mission_proposals (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    agent_id UUID REFERENCES ops_agents(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    proposed_steps JSONB DEFAULT '[]',
    priority TEXT DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled')),
    rejection_reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: Missions
-- Approved proposals become missions
CREATE TABLE IF NOT EXISTS ops_missions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    proposal_id UUID REFERENCES ops_mission_proposals(id),
    title TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'running', 'succeeded', 'failed', 'cancelled')),
    created_by UUID REFERENCES ops_agents(id),
    assigned_to UUID REFERENCES ops_agents(id),
    priority TEXT DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
    due_date TIMESTAMPTZ,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: Mission Steps
-- Concrete execution steps for each mission
CREATE TABLE IF NOT EXISTS ops_mission_steps (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    mission_id UUID REFERENCES ops_missions(id) ON DELETE CASCADE,
    agent_id UUID REFERENCES ops_agents(id),
    step_order INTEGER NOT NULL,
    kind TEXT NOT NULL CHECK (kind IN (
        'draft_content', 'review_code', 'post_social', 'run_analysis',
        'create_ads', 'research', 'write_code', 'send_email',
        'create_landing_page', 'optimize_campaign', 'general'
    )),
    description TEXT NOT NULL,
    input_data JSONB DEFAULT '{}',
    output_data JSONB DEFAULT '{}',
    status TEXT DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'blocked')),
    error_message TEXT,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: Agent Events
-- Event stream for agent actions and communications
CREATE TABLE IF NOT EXISTS ops_agent_events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    agent_id UUID REFERENCES ops_agents(id) ON DELETE CASCADE,
    mission_id UUID REFERENCES ops_missions(id) ON DELETE SET NULL,
    step_id UUID REFERENCES ops_mission_steps(id) ON DELETE SET NULL,
    kind TEXT NOT NULL CHECK (kind IN (
        'proposal_created', 'proposal_approved', 'proposal_rejected',
        'mission_started', 'mission_completed', 'mission_failed',
        'step_started', 'step_completed', 'step_failed',
        'content_published', 'code_committed', 'alert', 'decision_requested'
    )),
    title TEXT NOT NULL,
    summary TEXT,
    tags TEXT[] DEFAULT '{}',
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- CONTENT & ASSETS TABLES
-- ============================================

-- Table: Content Library
-- All content assets created by agents
CREATE TABLE IF NOT EXISTS ops_content (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('blog_post', 'social_post', 'email', 'landing_page', 'ad_copy', 'documentation')),
    platform TEXT,
    content TEXT NOT NULL,
    metadata JSONB DEFAULT '{}',
    version INTEGER DEFAULT 1,
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'review', 'approved', 'published', 'archived')),
    created_by UUID REFERENCES ops_agents(id),
    mission_id UUID REFERENCES ops_missions(id),
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: Campaign Tracking
-- Marketing campaigns and their performance
CREATE TABLE IF NOT EXISTS ops_campaigns (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    platform TEXT NOT NULL CHECK (platform IN ('meta', 'google', 'linkedin', 'x', 'email')),
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'paused', 'completed')),
    budget DECIMAL(10,2),
    start_date DATE,
    end_date DATE,
    metrics JSONB DEFAULT '{}',
    mission_id UUID REFERENCES ops_missions(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- INDEXES FOR PERFORMANCE
-- ============================================

CREATE INDEX IF NOT EXISTS idx_proposals_agent ON ops_mission_proposals(agent_id);
CREATE INDEX IF NOT EXISTS idx_proposals_status ON ops_mission_proposals(status);
CREATE INDEX IF NOT EXISTS idx_missions_status ON ops_missions(status);
CREATE INDEX IF NOT EXISTS idx_missions_assigned ON ops_missions(assigned_to);
CREATE INDEX IF NOT EXISTS idx_steps_mission ON ops_mission_steps(mission_id);
CREATE INDEX IF NOT EXISTS idx_steps_status ON ops_mission_steps(status);
CREATE INDEX IF NOT EXISTS idx_events_agent ON ops_agent_events(agent_id);
CREATE INDEX IF NOT EXISTS idx_events_created ON ops_agent_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_content_status ON ops_content(status);
CREATE INDEX IF NOT EXISTS idx_campaigns_status ON ops_campaigns(status);

-- ============================================
-- RLS POLICIES (Row Level Security)
-- ============================================

ALTER TABLE ops_agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_mission_proposals ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_missions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_mission_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_agent_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_campaigns ENABLE ROW LEVEL SECURITY;

-- Allow authenticated access (agents can read/write their own data)
CREATE POLICY "Allow authenticated access" ON ALL TABLES FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- ============================================
-- FUNCTIONS & TRIGGERS
-- ============================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply updated_at triggers
CREATE TRIGGER update_ops_agents_updated_at BEFORE UPDATE ON ops_agents
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_ops_mission_proposals_updated_at BEFORE UPDATE ON ops_mission_proposals
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_ops_missions_updated_at BEFORE UPDATE ON ops_missions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_ops_mission_steps_updated_at BEFORE UPDATE ON ops_mission_steps
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_ops_content_updated_at BEFORE UPDATE ON ops_content
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_ops_campaigns_updated_at BEFORE UPDATE ON ops_campaigns
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Function to create event when proposal status changes
CREATE OR REPLACE FUNCTION proposal_status_changed()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status != OLD.status THEN
        INSERT INTO ops_agent_events (agent_id, kind, title, summary)
        VALUES (
            NEW.agent_id,
            CASE NEW.status
                WHEN 'approved' THEN 'proposal_approved'
                WHEN 'rejected' THEN 'proposal_rejected'
                ELSE 'proposal_created'
            END,
            'Proposal: ' || NEW.title,
            'Status changed from ' || OLD.status || ' to ' || NEW.status
        );
    END IF;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER proposal_status_trigger AFTER UPDATE ON ops_mission_proposals
    FOR EACH ROW EXECUTE FUNCTION proposal_status_changed();

-- ============================================
-- INITIAL DATA: DEFAULT AGENTS
-- ============================================

INSERT INTO ops_agents (name, role, capabilities, status) VALUES
    ('orchestrator', 'Meta-Agent', ARRAY['coordination', 'routing', 'reporting'], 'active'),
    ('coder', 'Development', ARRAY['write_code', 'review_code', 'debug', 'pr_management'], 'active'),
    ('marketer', 'Content', ARRAY['write_content', 'email_marketing', 'landing_pages'], 'active'),
    ('social', 'Social Media', ARRAY['post_social', 'engage', 'community'], 'active'),
    ('ads', 'Paid Acquisition', ARRAY['create_ads', 'optimize_campaigns', 'a_testing'], 'active'),
    ('research', 'Intelligence', ARRAY['research', 'analysis', 'competitor_tracking'], 'active'),
    ('ops', 'Operations', ARRAY['note_taking', 'task_tracking', 'organization'], 'active')
ON CONFLICT (name) DO NOTHING;
