#!/usr/bin/env python3
"""
AddOnQuote Morning Report Generator
Runs automatically for the AddOnQuote agent
"""

import sys
import os
import json
import redis
from datetime import datetime, timedelta

def get_redis_stats():
    """Get posting stats from Redis"""
    try:
        r = redis.Redis(host='localhost', port=6379, db=0, decode_responses=True)
        
        total = r.get("stats:addonquote:posts:total") or 0
        today = r.get("stats:addonquote:posts:today") or 0
        threads = r.get("stats:addonquote:threads:total") or 0
        
        return {
            'posts_today': today,
            'posts_total': total,
            'threads': threads
        }
    except:
        return {'posts_today': '?', 'posts_total': '?', 'threads': '?'}

def get_pipeline_count():
    """Count available posts in pipeline"""
    try:
        with open('/Users/alfredoalvarez/.openclaw/social-automation/data/pipelines.json') as f:
            data = json.load(f)
        return len(data.get('ADDONQUOTE', []))
    except:
        return '?'

def generate_report():
    """Generate the morning report for AddOnQuote"""
    stats = get_redis_stats()
    pipeline = get_pipeline_count()
    today = datetime.now().strftime('%Y-%m-%d')
    
    report = f"""
**📊 ADDONQUOTE REPORT - {today}**

**Yesterday's Performance:**
- Posts: {stats['posts_today']} ({stats['posts_total']} lifetime)
- Threads: {stats['threads']}
- Pipeline: {pipeline} posts available

**Today's Goals:**
- [ ] Post 20 tweets (spread throughout day)
- [ ] Engage with 10+ roofers/contractors
- [ ] Respond to all inquiries within 1 hour
- [ ] Push for first trial conversion

**Lead Gen Status:**
- X Engagement: {'✅ Active' if int(stats['posts_today']) > 0 else '❌ No posts yesterday'}
- DM Conversations: Check Notion
- Trials: 0 (no trials yet)
- Paid: $0 (no conversions)

**MRR Progress:** $0

---
*Generated by AddOnQuote Agent*
"""
    
    return report

if __name__ == "__main__":
    print(generate_report())