#!/usr/bin/env python3
"""
Side Quest Studios Morning Report Generator
Runs automatically for the Side Quest Studios agent
"""

import sys
import os
import json
import redis
from datetime import datetime, timedelta

def get_redis_stats():
    """Get posting stats from Redis"""
    try:
        r = redis.Redis(host='localhost', port=6379, db=0, decode_responses=True)
        
        total = r.get("stats:sidequest:posts:total") or 0
        today = r.get("stats:sidequest:posts:today") or 0
        threads = r.get("stats:sidequest:threads:total") or 0
        
        return {
            'posts_today': today,
            'posts_total': total,
            'threads': threads
        }
    except:
        return {'posts_today': '?', 'posts_total': '?', 'threads': '?'}

def get_pipeline_count():
    """Count available posts in pipeline"""
    try:
        with open('/Users/alfredoalvarez/.openclaw/social-automation/data/pipelines.json') as f:
            data = json.load(f)
        return len(data.get('SIDEQUEST', []))
    except:
        return '?'

def generate_report():
    """Generate the morning report for Side Quest Studios"""
    stats = get_redis_stats()
    pipeline = get_pipeline_count()
    today = datetime.now().strftime('%Y-%m-%d')
    
    report = f"""
**📊 SIDE QUEST STUDIOS REPORT - {today}**

**Yesterday's Performance:**
- Posts: {stats['posts_today']} ({stats['posts_total']} lifetime)
- Threads: {stats['threads']}
- Pipeline: {pipeline} posts available

**Subsidiary Performance:**
- AddOnQuote: Check AddOnQuote agent report
- Sheet It Now: Check Sheet It Now agent report

**Today's Goals:**
- [ ] Post 20 tweets (spread throughout day)
- [ ] Cross-promote subsidiaries (every 5th post)
- [ ] Engage with 10+ indie hackers/makers
- [ ] Share one build-in-public update
- [ ] Respond to all DMs within 1 hour

**Brand Building Status:**
- X Engagement: {'✅ Active' if int(stats['posts_today']) > 0 else '❌ No posts yesterday'}
- Follower Growth: Check X analytics
- Community: DM conversations ongoing

**MRR (Combined):** $0

---
*Generated by Side Quest Studios Agent*
"""
    
    return report

if __name__ == "__main__":
    print(generate_report())